services:
  backend:
    build: 
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: strongerme
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./react-app
    container_name: frontend-1
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  postgres-data: {}
